### ISSUE TITLE
多娜多娜官中1.01版ain文件无法提取

### ISSUE THREAD

**Issue by ghost** [differentrain/AliceToolsGui#1]
* AliceToolsGui 版本 1.1.0
* alice-tools 版本 0.9.0

使用AliceToolsGui提取多娜多娜官中1.01版文件dohnadohna.ain时，采取UTF-8等编码时报告ERROR: iconv: Invalid argument；采取OEM美国编码时，提取结果为乱码。

尝试所有编码后，结果均为报错或乱码。

可以正常提取Rance10.ain文件。

大佬怎么看这个问题？

**Comment by differentrain** [comment]
> * AliceToolsGui 版本 1.1.0
> * alice-tools 版本 0.9.0
> 
> 使用AliceToolsGui提取多娜多娜官中1.01版文件dohnadohna.ain时，采取UTF-8等编码时报告ERROR: iconv: Invalid argument；采取OEM美国编码时，提取结果为乱码。
> 
> 尝试所有编码后，结果均为报错或乱码。
> 
> 可以正常提取Rance10.ain文件。
> 
> 大佬怎么看这个问题？

多次尝试辛苦了。这是此汉化版特有的问题。
`ERROR: iconv: Invalid argument；` 提示的意思表明这确实是编码错误。
根据[Ain格式](https://haniwa.technology/tech/ain4.html)的说明，它通常以`0x5D3E3`作为随机数种子，通过[梅森旋转算法](https://zh.wikipedia.org/wiki/%E6%A2%85%E6%A3%AE%E6%97%8B%E8%BD%AC%E7%AE%97%E6%B3%95)生成的随机序列依次对原始内容进行`XOR(异或)`加密。
根据错误提示，猜测这里或许是汉化版本中修改了这个随机数，或者添加了其他加密算法。
汉化版进程本身加了壳，影响逆向分析，脱壳又意义不大，所以我没有进一步对此问题进行分析。
想要解决此问题，最佳方式可能是尝试联系多娜多娜的中文化团队……

**Comment by ghost** [comment]
感谢大佬的解释！
